Neural Network Sederhana

Referensi : [https://towardsdatascience.com/deep-learning-with-python-neural-networks-complete-tutorial-6b53c0b06af0]

In [ ]:
import numpy
import random

In [ ]:
input_value = np.array([[1.5],[0.5],[2.0]])
input_value.shape
input_value

array([[1.5],
       [0.5],
       [2. ]])

In [ ]:
output_value = np.array([1])
# output_value.shape()
output_value.reshape(1,1)
output_value

array([1])

In [ ]:
for i in range(1):
  i = random.randrange(0,10)
  # print(i)

weights = np.array([i])
# weights = np.array([4,9])
weights

array([7])

In [ ]:
#add bias
bias = 0.3

In [ ]:
#Fungsi aktivasi
from scipy.stats.morestats import exp

def sigmoid(x):
  return 1/(1+exp(-x))
  # return ((exp(x)-exp(-x)) / (exp(x)+exp(-x)))

In [ ]:
#derifatif fungsi sigmoid
# chain-rule untuk gradient descent
def der_sigmoid(x):
  return sigmoid(x) * (1-sigmoid(x))

In [ ]:
# a = [1.5,0.5,2.0]
# b = [4,9]

# sum = 0
# for i in a:
#   e = i * b[0]
#   sum += e
#   print(e)
# print(sum)

6.0
2.0
8.0
16.0


In [ ]:
for epochs in range(100):
  input = input_value

  # Forward propagation
  weighted_sum = np.dot(input, weights)
  first_output = sigmoid(weighted_sum)
  print('first_output :', first_output)

  # Mean square error (MSE)
  error = first_output - output_value
  total_error = np.square(np.subtract(first_output, output_value)).mean()

  # Menggabungkan kalkulasi gradient descent
  first_der = error
  second_der = der_sigmoid(first_output)  #derivative sigmoid
  derivative = first_der * second_der

  # Backward propagation
  t_input = input_value.T
  final_derivative = np.dot(t_input, derivative)

  # Mean square error (MSE)
  error2 = final_derivative - input
  total_error2 = np.square(np.subtract(final_derivative, input)).mean()

  #Update weights
  weights = weights - 0.05 * final_derivative
  print('weights :', weights)

  #Update bias
  for i in derivative:
    bias = bias - 0.05 * i

print('First output after forward propagation :', first_output)
print('MSE after forward propagation :',total_error)
print('Update weight after backward propagation :', weights)
print('MSE after backward propagation :',total_error2)

print('Weights : ', weights)
print('Bias : ', bias)

first_output : [0.99997246 0.97068777 0.99999917]
weights : [7.00014644]
first_output : [0.99997247 0.97068985 0.99999917]
weights : [7.00029287]
first_output : [0.99997248 0.97069194 0.99999917]
weights : [7.00043929]
first_output : [0.99997248 0.97069402 0.99999917]
weights : [7.0005857]
first_output : [0.99997249 0.9706961  0.99999917]
weights : [7.0007321]
first_output : [0.99997249 0.97069818 0.99999917]
weights : [7.00087849]
first_output : [0.9999725  0.97070026 0.99999917]
weights : [7.00102486]
first_output : [0.99997251 0.97070235 0.99999917]
weights : [7.00117123]
first_output : [0.99997251 0.97070443 0.99999917]
weights : [7.00131759]
first_output : [0.99997252 0.97070651 0.99999917]
weights : [7.00146393]
first_output : [0.99997252 0.97070859 0.99999917]
weights : [7.00161027]
first_output : [0.99997253 0.97071067 0.99999917]
weights : [7.00175659]
first_output : [0.99997254 0.97071275 0.99999917]
weights : [7.0019029]
first_output : [0.99997254 0.97071483 0.99999917]
weig

In [ ]:
#Predictions
pred = np.array([0.1])
result = np.dot(pred, weights) + bias
resClass = sigmoid(result)
print(resClass)

if (resClass <= 0.5):
  print('Class Prediction :', 'Class A')
if (resClass >0.5):
  print('Class Prediction :', 'Class B')

0.7370296537206874
Class Prediction : Class B
